spring.application.name=spendwise
spring.datasource.url=jdbc:postgresql://localhost:5432/spendwise
spring.datasource.username=postgres
spring.datasource.password=Computer78**
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.type.preferred_instant_jdbc_type=TIMESTAMP

server.port=8080

jwt.secret=spendwise-super-secret-key-change-this-in-production-min-32-chars
jwt.expiration=86400000